### ISSUE TITLE
Version of fullcalendar.js is quite old, so missing some features

### ISSUE THREAD

**Issue by zarocknz** [peavers/silverstripe-full-calendar#10]
Discovered the version of fullcalendar javascript library in this module is quite old (2.3.0) so some features we expected to use are missing.

Please consider updating to the latest version of fullcalendar.io (3.5.1 at time of writing).

Thank you.

**Comment by peavers** [comment]
Hello, 

I've just moved this quickly into webpack and updated to the latest versions of all JS libraries. It's pretty rough and dirty but should do the trick.
